language: php

sudo: false

dist: trusty

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=latest WP_MULTISITE=1
    - WP_VERSION=4.7 WP_MULTISITE=0
    - WP_VERSION=4.6 WP_MULTISITE=0
    - WP_VERSION=4.5 WP_MULTISITE=0

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=trunk
    - php: 7.0
    - php: 5.6
    - php: 5.3
      dist: precise

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi

script: phpunitphpunit/phpunit=4.8.*"
    fi

script: phpunit